import visa
import numpy as np
rm = visa.ResourceManager()
#rm = visa.ResourceManager('@py')
rm.list_resources()
inst = rm.open_resource('GPIB0::24::INSTR')
print(inst.query("*IDN?"))

inst.write(':ROUT: REAR')
print(inst.query(':ROUT?'))
inst.write(':SENS:FUNC:CONC OFF')
inst.write(':SOUR:FUNC CURR')
inst.write(':SENS:FUNC VOLT:DC')
inst.write(':SENS:VOLT:PROT 10')
inst.write(':SOUR:CURR:START 1E-3')
inst.write(':SOUR:CURR:STOP 10E-3')
inst.write(':SOUR:CURR:STEP 1E-3')
inst.write(':SOUR:CURR:MODE SWE')
inst.write(':SOUR:SWE:RANG AUTO')
inst.write(':SOUR:SWE:SPAC LIN')
inst.write(':TRIG:COUN 10')
inst.write(':SOUR:DEL 0.1')
inst.write(':OUTP ON')
values = np.array(inst.query_ascii_values(':READ?'))
inst.write(':OUTP OFF')
